[tool.poetry]
name = "fintubes"
version = "0.1.0"
description = "analysis package for finnned tube condensers"
authors = ["Martyn <1931150@brunel.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.19"
seaborn = "0.11.1"
statsmodels = "^0.12.2"
pandas = "1.0"
scikit-learn = "^0.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
